# Generated by Django 5.0.6 on 2026-09-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('freedompay', 'Freedom Pay'), ('paybot', 'PayBot')], max_length=30)),
                ('webhook_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('freedompay', 'Freedom Pay'), ('paybot', 'PayBot')], default='paybot', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Не оплачен'), ('cancelled', 'Отменен'), ('expired', 'Истек'), ('refunded', 'Возвращен')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='processedwebhook',
            constraint=models.UniqueConstraint(fields=('provider', 'webhook_id'), name='unique_provider_webhook'),
        ),
    ]
