# Generated by Django 5.0.6 on 2026-08-23 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('text', 'Текст'), ('video', 'Видео'), ('assignment', 'Задание'), ('quiz', 'Тест'), ('file', 'Файл'), ('project', 'Проект')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, verbose_name='Текстовый контент')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Длительность (мин)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный урок (превью)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order', 'id'],
            },
        ),
    ]
